# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.cache/wt [current_project]
set_property parent.project_path H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/build/elf/vanilla_test.elf
set_property SCOPED_TO_REF cpu [get_files -all H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/build/elf/vanilla_test.elf]
set_property SCOPED_TO_CELLS U0/microblaze_I [get_files -all H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/build/elf/vanilla_test.elf]
read_verilog H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/sys/bridge/chu_io_map.svh
set_property file_type "Verilog Header" [get_files H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/sys/bridge/chu_io_map.svh]
read_verilog -library xil_defaultlib -sv {
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/uart/baud_gen.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/sseg/ch04_15_disp_mux.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/mmio_basic/chu_gpi.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/mmio_basic/chu_gpo.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/sys/bridge/chu_mcs_bridge.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/mmio_support/chu_mmio_controller.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/mmio_basic/chu_timer.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/uart/chu_uart.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/sseg/counter.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/mmio_support/fifo/fifo.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/mmio_support/fifo/fifo_ctrl.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/sseg/list_ch03_14_hex_to_sseg.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/sys/subsys/mmio_sys_vanilla.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/mmio_support/fifo/reg_file.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/sseg/register.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/sseg/sseg_disp.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/sseg/sseg_wrapper.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/uart/uart.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/uart/uart_rx.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/mmio/uart/uart_tx.sv
  H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/imports/code_listing_sv/fpga_mcs_sv_src/hdl/sys/top/mcs_top_vanilla.sv
}
read_ip -quiet H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/cpu.xci
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/ip/ip_2/bd_3914_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/ip/ip_3/bd_3914_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/ip/ip_6/bd_3914_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/ip/ip_7/bd_3914_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/bd_0/bd_3914_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/cpu_board.xdc]
set_property used_in_implementation false [get_files -all h:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/cpu_ooc.xdc]
set_property is_locked true [get_files H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/sources_1/ip/cpu/cpu.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/constrs_1/imports/constraint/Nexys4_DDR_chu.xdc
set_property used_in_implementation false [get_files H:/SoC_Labs/sseg_soc/nexys4_sv_vanilla/nexys4_sv_vanilla.srcs/constrs_1/imports/constraint/Nexys4_DDR_chu.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mcs_top_vanilla -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mcs_top_vanilla.dcp

catch { report_utilization -file mcs_top_vanilla_utilization_synth.rpt -pb mcs_top_vanilla_utilization_synth.pb }
